# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 권종범
title: Python 백엔드 엔지니어
email: bolk9652@naver.com
# website: https://github.com/by-Exist

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username, stackoverflow_username, dribbble_username, facebook_username, flickr_username, instagram_username, linkedin_username, xing_username, pinterest_username, youtube_username, googleplus_username, orcid_username
github_username: by-Exist

# Additional icon links
additional_links:
  - title: tistory
    icon: fas fa-globe # (https://fontawesome.com/icons?d=gallery&m=free)
    url: https://by-exist.tistory.com/

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  &nbsp;&nbsp;Django를 활용한 파이썬 웹 백엔드 개발자입니다.

  &nbsp;&nbsp;'파이썬의 선'에 등장하는 아래의 문장을 늘 마음에 새겨두고 있습니다.

  > &nbsp;&nbsp;문제를 해결할 하나의 - 바람직하고 유일한 - 명백한 방법이 있을 것이다. 비록 처음에는 명백해보이지 않을 수도 있겠지만.

# content:
#   # Example Section
#   - title: Example
#     layout: list # or text
#     content:
#       - layout: left # right, top-middle
#         title: Example Title
#         sub_title: Some Example Sub Title
#         caption: 1234.56 - 1234.56
#         link: example.com
#         link_text: example link display text
#         additional_links:
#           - title: icon title
#             icon: fab fa-github # https://fontawesome.com/v5.15/icons
#             url: www.icon-link.com
#         quote: >
#           Summary text
#         description: | # this will include new lines to allow paragraphs
#           Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.

content:
  # Skill Section
  - title: Skill
    layout: list
    content:
      - layout: top-middle
        title: Backend
        sub_title: |
          <mark style="background-color:rgb(0, 102, 204)">Python</mark>
          <mark style="background-color:rgb(0, 102, 204)">DRF</mark>
          <mark>Postgres</mark>
          <mark>Nginx</mark>
      - layout: top-middle
        title: Devops
        sub_title: |
          <mark>Docker</mark>
          <mark>Github Action</mark>
      - layout: top-middle
        title: Other
        sub_title: |
          <mark>VSCode</mark>
          <mark>Git</mark>
          <mark>Vultr</mark>

  # Project Section
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Django Skeleton
        sub_title: DRF로 개발할 API 서비스의 뼈대
        caption: 2021.5 ~ 2021.7
        additional_links:
          - title: github link
            icon: fab fa-github
            url: https://github.com/by-Exist/django-skeleton
          - title: drf-custom github link
            icon: fab fa-github
            url: https://github.com/by-Exist/django-skeleton/blob/master/backend/utils/drf_custom/README.md
          - title: website link
            icon: fas fa-globe
            url: https://exampleapp.kro.kr/v1/schema/swagger/
        description: |
          &nbsp;&nbsp;Django를 활용하여 API 서비스를 개발할 때 사용하게 될 뼈대 파일입니다.

          &nbsp;&nbsp;Django 및 DRF의 설정, API 페이지, Docker 및 Docker-compose를 활용한 서비스 개발 및 배포, Nginx 설정, Domain 대여 및 SSL 발급, Github Action을 활용한 CI 과정 등이 포함되어 있습니다.

          &nbsp;&nbsp;**[Google API Design Guide](https://cloud.google.com/apis/design)**에 등장하는 API 동작 개념들을 구현하기 위해 DRF의 코드를 직접 살펴보며 유틸성 코드를 작성하였습니다.

          &nbsp;&nbsp;아이콘을 클릭하여 해당 뼈대로 구현된 [**예제 사이트(Swagger)**](https://exampleapp.kro.kr/v1/schema/swagger/)를 확인할 수 있습니다.
      - layout: left
        title: Piku API Clone
        sub_title: Piku 서비스의 API를 클론
        caption: 2021.3 ~ 2021.4
        additional_links:
          - title: github link
            icon: fab fa-github
            url: https://github.com/by-Exist/piku_backend_api
        description: |
          &nbsp;&nbsp;Piku 이미지 월드컵 사이트를 클론하여 API를 작성하였습니다.

          &nbsp;&nbsp;Django Debug Toolbar를 활용한 ORM 최적화 및 프로젝트의 효율적인 구조, Swagger를 사용한 API 문서화 등을 학습하게 되었습니다.
      - layout: left
        title: Pinterest Clone
        sub_title: Django를 활용한 Pinterest 서비스 Clone
        caption: 2021.1 ~ 2021.2
        additional_links:
          - title: github link
            icon: fab fa-github
            url: https://github.com/by-Exist/Pinterest_Clone
        description: |
          &nbsp;&nbsp;Django가 제공하는 기본 기능들을 적극적으로 활용하여 Pinterest 서비스를 클론하였습니다.

          &nbsp;&nbsp;컨테이너 기술이 개발 프로세스에 있어 뛰어난 생산성을 보장해준다는 점을 체감할 수 있었습니다. 앞으로 학습해야 할 것들이 무엇인지 전반적으로 확인할 수 있었던 프로젝트입니다.
      - layout: left
        title: Instagram Clone
        sub_title: Django를 활용하여 Instagram 서비스를 Clone
        caption: 2020.9 ~ 2021.12
        additional_links:
          - title: frontend github link
            icon: fab fa-github
            url: https://github.com/by-Exist/ins_frontend
          - title: backend github link
            icon: fas fa-github
            url: https://github.com/by-Exist/ins_backend
        description: |
          &nbsp;&nbsp;Instagram 서비스를 클론한 사이트를 제작하였습니다.

          &nbsp;&nbsp;Django와 React를 활용하여 개발되었으며, 프론트엔드와 백엔드의 분리된 과정에서의 개발과 배포에 얽힌 여러 단계를 밟아가며 전체적인 웹 개발 프로세스를 파악하였습니다.
      - layout: left
        title: Cat Humor School
        sub_title: 국비지원 과정 중 진행된 웹 개발 팀 프로젝트
        caption: 2020.7 ~ 2020.8
        additional_links:
          - title: github link
            icon: fab fa-github
            url: https://github.com/by-Exist/school_projects
          - title: bigmacaron github link
            icon: fas fa-globe
            url: https://github.com/bigmacaron/cat_humor_school
        description: |
          &nbsp;&nbsp;국비지원교육 과정에서 진행한 팀 프로젝트입니다. Flask와 SQLite, requests, beautifulsoup을 활용하여 개발되었습니다.

          &nbsp;&nbsp;타 유머 사이트의 포스팅을 크롤링하는 모듈 및 백엔드 전반을 담당하였습니다. 기본 웹 개발 지식에 한계를 느껴 해당 팀 프로젝트는 토론 하에 중단되었습니다. Django를 학습하게 된 계기가 되었습니다.

  # Education Section
  - title: Education
    layout: list
    content:
      - layout: right
        title: 작정하고 장고
        caption: 2021.02 - 2021.04
        link: https://www.inflearn.com/
        quote: >
          Django 심화
        description: |
          &nbsp;&nbsp;Django의 기본 기능을 적극 활용하여 Pinterest 서비스를 클론하였습니다.

          &nbsp;&nbsp;Docker를 활용하여 서비스를 배포하는 과정에서 컨테이너 기술이 현대 개발에 있어 큰 부분을 차지하고 있다는 점을 체감할 수 있었습니다.
      - layout: right
        title: 리액트와 함께 장고 시작하기 Complete
        caption: 2020.09 ~ 2021.02
        link: https://educast.com/
        quote: >
          Django, React 기초
        description: |
          &nbsp;&nbsp;React와 Django를 활용하여 웹 서비스를 개발하는 방법을 학습하였습니다.

          &nbsp;&nbsp;Django의 기초 개념, DRF와 React를 활용한 서비스 개발, 서비스 개발 과정의 전반적인 흐름을 경험할 수 있었습니다.
      - layout: right
        title: 국비지원학원
        sub_title: 파이썬/자바/프레임워크 기반 공공 데이터 활용 인공지능/빅데이터 서비스
        caption: 2019.12 ~ 2020.9
        link: http://hkit.kr/
        quote: >
          프로그래밍 기초
        description: |
          &nbsp;&nbsp;국비지원학원 과정을 통해 프로그래머로써 갖추어야 할 기본기를 학습하였습니다. 

          &nbsp;&nbsp;Java, Python, SQL을 위주로 학습이 진행되었으며, 두번째로 진행한 팀 프로젝트에서 flask를 활용한 웹 개발을 경험하고 진로를 결정하게 되었습니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
